package com.example.quiz_app.ui

import androidx.compose.animation.core.LinearEasing
import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.geometry.CornerRadius
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.center
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import kotlin.math.PI
import kotlin.math.cos
import kotlin.math.sin

/**
 * Draws a full-screen "northern lights" background and places content on top.
 * Canvas to draw a linear gradient background from top left to bottom right using predefined colors
 *
 * Accepts an optional [modifier] so calling code in other files can control layout/size.
 */
@Composable
fun NorthernLightsBackground(modifier: Modifier = Modifier, content: @Composable () -> Unit) {
    Box(modifier = modifier.fillMaxSize()) {
        Canvas(modifier = Modifier.fillMaxSize()) {
            val colors = listOf(
                Color(0xFF0D0D26),
                Color(0xFF1A1A4D),
                Color(0xFF003366),
                Color(0xFF004C99),
                Color(0xFF0D0D26)
            )   //Generated by AI and adjusted a little to look better
            drawRect(
                brush = Brush.linearGradient(
                    colors = colors,
                    start = Offset(0f, 0f),
                    end = Offset(size.width, size.height)
                )
            )
        }
        content()
    }
}

/**
 * A function that creates an animated glowing button.
 * The button is styled with a glowing gradient border that has an infinite animation loop.
 *
 * @param onClick A lambda function to be executed when the button is clicked.
 * @param text The text to be displayed inside the button.
 * @param modifier A [Modifier] to be applied to the button for layout, decoration, or additional behavior.
 */
@Composable
fun AnimatedGlowingButton(
    onClick: () -> Unit,
    text: String,
    modifier: Modifier = Modifier
) {
    val infiniteTransition = rememberInfiniteTransition(label = "angle")

    // Supporting animation loop that will be used to change gradient
    val angle by infiniteTransition.animateFloat(
        initialValue = 0f,
        targetValue = (2 * PI).toFloat(), //full rotation
        animationSpec = infiniteRepeatable(
            animation = tween(5000, easing = LinearEasing),
            repeatMode = RepeatMode.Restart
        ),
        label = "angle"
    )

    // AI generated colors and modified a little to look better
    val colors = listOf(
        Color(0xFF00FFFF),
        Color(0xFFFF00FF),
        Color(0xFF00FF00),
        Color(0xFFFFFF00),
        Color(0xFF00FFFF)
    )

    val cornerRadius = 50.dp

    // Button with transparent background 
    // and glowing gradient border using sweep gradient defined earlier
    Button(
        onClick = onClick,
        modifier = modifier
            .clip(RoundedCornerShape(cornerRadius)) //prevents drawing outside of corners
            .drawBehind {
                val radius = size.width
                // Calculates a point that orbits around the button’s center
                val center = Offset(
                    x = size.center.x + radius * cos(angle),
                    y = size.center.y + radius * sin(angle)
                )

                // Creates a sweep gradient that rotates around the center point and distributes colors
                val brush = Brush.sweepGradient(colors, center = center)

                drawRoundRect(
                    brush = brush,
                    style = Stroke(width = 15f),
                    cornerRadius = CornerRadius(cornerRadius.toPx())
                )
            },
        colors = ButtonDefaults.buttonColors(
            containerColor = Color.Transparent,
            contentColor = Color.White
        )
    ) {
        Text(text = text, modifier = Modifier.padding(8.dp))
    }
}

/**
 * A custom function that displays a progress bar with text inside.
 *
 * @param progress The fraction of progress to display on the progress bar (a value between 0 and 1).
 * @param text The text to display inside the progress bar.
 */
@Composable
fun CustomProgressBar(progress: Float, text: String) {
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .height(24.dp)
            // The background of the progress bar (the track)
            .background(
                MaterialTheme.colorScheme.primary.copy(alpha = 0.3f),
                RoundedCornerShape(12.dp)
            )
            .clip(RoundedCornerShape(12.dp)),
        contentAlignment = Alignment.CenterStart
    ) {
        // The progress indicator
        Box(
            modifier = Modifier
                .fillMaxWidth(fraction = progress)
                .height(24.dp)
                .background(MaterialTheme.colorScheme.primary, RoundedCornerShape(12.dp))
        )
        // The text overlay
        Text(
            text = text,
            color = Color.White,
            textAlign = TextAlign.Center,
            modifier = Modifier.fillMaxWidth()
        )
    }
}

//Previews for background and button, as we talked about preview in the last lecture on 29.1.
@Preview(showBackground = true)
@Composable
fun NorthernLightsBackgroundPreview() {
    NorthernLightsBackground {}
}

@Preview(showBackground = true)
@Composable
fun AnimatedGlowingButtonPreview() {
    NorthernLightsBackground {
        Box(modifier = Modifier
            .fillMaxSize()
            .padding(16.dp)) {
            AnimatedGlowingButton(onClick = {}, text = "Preview button")
        }
    }
}
